import { logger } from '../../lib/logger.js';
import { env } from '../../config/env.js';
import { buildProjectionContext, type ProjectionQuery } from './context.js';
import { runProjection, type SeriesPoint } from './model.js';
import { estimateYieldLoss, type YieldLossEstimate } from './yield-loss.js';
import { generateOutbreakNarrative, type OutbreakNarrative } from '../../integrations/gemini.js';
import { knownCrops } from '../risk/crop-profiles.js';

export interface OutbreakProjectionResult {
  query: ProjectionQuery;
  generatedAt: string;
  crop: string | null;
  population: { fieldsInArea: number; farmersInArea: number; areaAcresTotal: number };
  carryingCapacity: number;
  medianDaysSinceSown: number | null;
  series: SeriesPoint[];
  yieldLossEstimate: YieldLossEstimate;
  narrative: OutbreakNarrative | null;
  modelDisclosure: { method: string; sources: string[] };
}

/**
 * Same discipline as insights.service.ts's groundCards(): don't just trust
 * free text. This schema has no structured fieldName-style slot to null out,
 * so the check here is a real one that fits free text — scan for any OTHER
 * known crop name than the real context crop (a concrete hallucination this
 * feature is prone to: attributing the outbreak to the wrong crop). If found,
 * drop the narrative rather than show a misattributed one — the quantitative
 * series and yieldLossEstimate remain the authoritative result either way.
 */
function groundNarrative(n: OutbreakNarrative, ctx: { crop: string | null }): OutbreakNarrative | null {
  if (!ctx.crop) return n;
  const text = `${n.headline} ${n.summary}`.toLowerCase();
  const wrongCrop = knownCrops.find(
    (c) => c !== ctx.crop && new RegExp(`\\b${c}\\b`, 'i').test(text),
  );
  if (wrongCrop) {
    logger.warn({ crop: ctx.crop, wrongCrop }, 'outbreak narrative mentioned a different crop — dropping it');
    return null;
  }
  return n;
}

export async function buildOutbreakProjection(query: ProjectionQuery): Promise<OutbreakProjectionResult> {
  const ctx = await buildProjectionContext(query);
  const { points: series, finalLevel } = runProjection(ctx, query.horizonDays);
  const yieldLossEstimate = estimateYieldLoss(ctx.population.areaAcresTotal, finalLevel);

  let narrative: OutbreakNarrative | null = null;
  if (env.GEMINI_API_KEY) {
    try {
      const contextForModel = {
        crop: ctx.crop,
        mainThreats: ctx.mainThreats,
        topDiagnosis: ctx.topDiagnosis,
        district: query.district ?? null,
        observedHistoryWeekly: ctx.history,
        totalConfirmedInWindow: ctx.s0,
        population: ctx.population,
        carryingCapacity: ctx.carryingCapacity,
        projectionHorizonDays: query.horizonDays,
        series: series.map((s) => ({
          date: s.date,
          phase: s.phase,
          projectedCount: s.projectedCount,
          riskScore: s.riskScore,
          riskLevel: s.riskLevel,
        })),
        yieldLossEstimate,
      };
      const gen = await generateOutbreakNarrative(JSON.stringify(contextForModel));
      narrative = groundNarrative(gen.narrative, ctx);
    } catch (err) {
      logger.warn({ err }, 'outbreak narrative generation failed — returning quantitative result only');
    }
  }

  return {
    query,
    generatedAt: new Date().toISOString(),
    crop: ctx.crop,
    population: ctx.population,
    carryingCapacity: ctx.carryingCapacity,
    medianDaysSinceSown: ctx.medianDaysSinceSown,
    series,
    yieldLossEstimate,
    narrative,
    modelDisclosure: {
      method:
        "Deterministic logistic-growth model: each day's risk score comes from the same transparent " +
        'heuristic used elsewhere in this app (weather-driven fungal/pest pressure x crop growth-stage), ' +
        'mapped to a daily infection rate, applied as a discrete logistic step bounded by the real number ' +
        "of fields in the area. Days 1-7 use the live weather forecast; beyond day 7 the last forecast day's " +
        'conditions are held constant and marked "extrapolated" rather than shown as a forecast. The ' +
        'narrative is generated by Gemini strictly from this computed result, not from its own estimate.',
      sources: [
        'Plant Disease Models and Forecasting (Phytopathology / APS, 2023)',
        'Model-Based Forecasting of Agricultural Crop Disease Risk (Frontiers in Environmental Science, 2018)',
        'Patterns of Damage Functions: Crop Yield Loss (Plant Disease / APS)',
        'ICAR-IARI wheat pest/disease avoidable-loss studies',
      ],
    },
  };
}
